### ISSUE TITLE
No member addListener

### ISSUE THREAD

**Issue by chriship** [labatrockwell/ofxLibwebsockets#48]
I am trying to run the server examples but I get an error telling me that the server library does not have a member addListener.

server.addListener(this);

**Comment by robotconscience** [comment]
Can you confirm which example(s) + platform? I'm not able to replicate this bug. 

Thanks!

**Comment by chriship** [comment]
Ah, sorry. OF version 0.8.4. Windows. Visual Studio. example_server_echo.

The only addListener method I can see is in Client.h

**Comment by robotconscience** [comment]
Hm! Can you try re-generating the project from the projectGenerator? Sounds like it's for some reason not seeing Server.h (which is where that function is).

Make sure to follow the examples in the Readme, as you have to add one more thing (a preprocessor def) to make it work. Let me know if that fixes it! Can push an update next week once I'm back on my Win machine.

**Comment by chriship** [comment]
Hmm, for some reason the addListener and removeListener methods in Server.h were commented out (I must have done that). Sorry for the false alarm!
