### ISSUE TITLE
missing mention of openssl dependency?

### ISSUE THREAD

**Issue by bombarie** [labatrockwell/ofxLibwebsockets#49]
I don't see a reference to the dependency to openssl. Got a build error that these files were missing:

````
../../../addons/ofxLibwebsockets/libs/openssl/lib/osx/libcrypto.a
../../../addons/ofxLibwebsockets/libs/openssl/lib/osx/libssl.a
````

Had to get openssl, configure and build and then create that directory path and copy those generated files from `/usr/local/ssl/macos-x86_64/lib`. Hope I didn't miss something in your guide...

**Comment by robotconscience** [comment]
Ah! Is this in an example or from the project generator? OpenSSL is compiled into OF (which I didn't realize when I first built this lib!), so those links shouldn't be necessary. I've since removed the libs and links, but let me know where you're getting errors and I'll figure it out!

**Comment by bombarie** [comment]
It's generated by [Express Generator](http://expressjs.com/starter/generator.html), which I always use to quickly fire up a working Node.JS project and I think many others too. Can't try my Myo at the moment but I'll test the new code hopefully tonight. Thanks!

**Comment by bombarie** [comment]
Argh! This was the example project in the [https://github.com/mattfelsen/ofxMyoWebSockets](ofxMyoWebSockets) ofxaddon. I decided to get and compile openssl to comply with the dependencies of the project instead of blindly removing them. Did that now and it compiles fine. Nothing to do with your ofxLibwebsockets, yay! Thanks for the quick response.
