### ISSUE TITLE
windows lagging issue

### ISSUE THREAD

**Issue by liquidzym** [labatrockwell/ofxLibwebsockets#50]
i was testing with some of the examples,but got really lagging issue between the server&client,which version of libwebsockets are you using ,the v1.3-chrome37-firefox30? 

i did complied the older version which is v1.23-chrome32-firefox24,running really fast(not with current ofxLibwebsockets)

just wondering what's the issue might be
cheers

**Comment by robotconscience** [comment]
Hm! That's super weird. Are you running release or debug? Usually that's the issue for that type of drop. 

I believe the release lib is linked correctly in windows, but double check on that. For now we're running I believe the earlier release, will update over the next couple weeks.

**Comment by liquidzym** [comment]
both,the release&debug,but i'll double check on that,should be. otherwise it won't complied

**Comment by robotconscience** [comment]
Hm! It should compile with either–just give you a warning if you're running as Debug and using Release library. Keep me posted!

**Comment by liquidzym** [comment]
em,i'm sure i linked the right library,release with release.
i can post some short video later on in case you can look into it
thank you

**Comment by liquidzym** [comment]
sorry,i'm closing this and make another post.
