### ISSUE TITLE
unable to compile in codeblocks 12.11 - windows

### ISSUE THREAD

**Issue by kalwalt** [labatrockwell/ofxLibwebsockets#51]
Hi, its so much time that i didn't use OF and this addon but i think there is some changes in OF that  don't let me compile in Windows OS. I used this addon in the past on a linux64 machine, honestly i didn't remember if i try it on windows. But OF Project generator now is changed and you must setup  the linker, i added ( in release mode) the libs as you suggested ( i think you refer to visual studio in the readme.md) but in this way i can't compile the project. if l link it also the websocket.lib i can compile, the app start but i receive an error: 
>impossible to run the app because wbsocketts.dll is missed.

maybe it's needed to add a flag? or what else?
Thank you
Walter

**Comment by robotconscience** [comment]
Hello! I think you just need to edit the addon_config.mk and add the includes/links against win_cb. Check it out here: https://github.com/labatrockwell/ofxLibwebsockets/blob/master/addon_config.mk

That way, you could just use the project generator. I believe it's the same as visual studio, but I don't use CB so I'm not sure!

The big thing is you need to link against websockets_static.lib and you won't get that DLL error!

**Comment by kalwalt** [comment]
Thank you for the answer, probably setting addon_config.mk will solve the issue. I tested the addon in Visual Studio 2012 and all is fine. If i will able to solve it, i will create a pull request with all the changes. 
Stay tuned!
Walter

**Comment by robotconscience** [comment]
Cool, thank you! Will keep this open till your PR.

**Comment by kalwalt** [comment]
i added in addon_config.mk these lines:
>win_cb:
	# source files, these will be usually parsed from the file system looking
	# in the src folders in libs and the root of the addon. if your addon needs
	# to include files in different places or a different set of files per platform
	# they can be specified here
	ADDON_SOURCES += 

	# include search paths, this will be usually parsed from the file system
	# but if the addon or addon libraries need special search paths they can be
	# specified here separated by spaces or one per line using +=
	#ADDON_INCLUDES += libs/libwebsockets/include
	ADDON_INCLUDES += libs/libwebsockets/include/win32port
	ADDON_INCLUDES += libs/libwebsockets/include/win32port/win32helpers


	# when parsing the file system looking for include paths exclude this for all or
	# a specific platform
	ADDON_INCLUDES_EXCLUDE
	ADDON_LIBS += libs/libwebsockets/lib/win32/Release/websockets_static.lib
	ADDON_LIBS += libs/libwebsockets/lib/win32/Release/ZLIB.lib

but still i receive rid of errors as this:

>undefined reference to __security cookies

but i have a suspect that i can't use that libs you provide for Visual Studio because you compiled for VS. if i'm using codeblocks with a MiniWG compiler will probably fail. Do you confirm this?

**Comment by kalwalt** [comment]
but looking in libwebsockets , i'm not sure that is possible to compile the lib (i'm not very smart with cmake) with codeblocks under the GNU gcc compiler.
