### ISSUE TITLE
libwebsockets_serve_http_file arguments issue

### ISSUE THREAD

**Issue by liquidzym** [labatrockwell/ofxLibwebsockets#55]
according to the readme, you're using libwebsockets 1.3,so i did complied that under the vs,but it seems still mismatch with your current version,also causing this issue

libwebsockets_serve_http_file Function does not take 6 arguments
are you sure you're using the 1.3 version of libwebsockets?

cheers

**Comment by robotconscience** [comment]
Hello! That's a typo in the readme, actually. I'm working off of the [latest commit](https://github.com/warmcat/libwebsockets/commit/3ae1badae7a05e0982e0dfbcb078da3d4b92a81d) on RPi 1/2, OS X, and Windows. I don't think the linux libs have been updated yet, though.

The nice thing is that LWS 1.4+ includes a lws_config file that includes both the major version and the commit hash: https://github.com/labatrockwell/ofxLibwebsockets/blob/master/libs/libwebsockets/include/lws_config.h

**Comment by liquidzym** [comment]
ok,thanks,now its working. but windows seems not working properly.will digging up this
