### ISSUE TITLE
Example failed to set wsi socket options 

### ISSUE THREAD

**Issue by michela** [labatrockwell/ofxLibwebsockets#57]
None of my lws sketches work on Pi but they do work on Xcode. My Pi is a revision '000e' => 'Model B Revision 2.0 512MB', (Sony)

Any suggestions?

e.g for ofxLibwebsockets/example_client_hello_world

[verbose] [ofxLibwebsockets] connect: echo.websocket.org:80/:0
[verbose] [ofxLibwebsockets] Setting timeout 1
[verbose] [ofxLibwebsockets] LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS
[verbose] [ofxLibwebsockets] LWS_CALLBACK_PROTOCOL_INIT
[verbose] [ofxLibwebsockets] libwebsocket init success
[1436273357:2009] ERR: Failed to set wsi socket options
[ error ] [ofxLibwebsockets] client connection failed

Note - I recompiled libwebsockets and replaced lib as per published instructions. test-echo works fine just not the oFx examples
./libwebsockets-test-echo --client echo.websocket.org --ssl --port=443

**Comment by robotconscience** [comment]
Hm! Can you try testing w/o SSL? I don't know as many folks that have used that with the Pi. Looks like that's where that example is failing. Interesting that the libwebsockets version is working, though! 

Let me know if it works without SSL, and I'll see if there's anything in the lib that might mess that up.

**Comment by michela** [comment]
Testing without SSL. 
Worked out that I can only connect (copying from examples) if I have all three ka_ options.
        options.ka_time     = 1;
        options.ka_probes   = 1;
        options.ka_interval = 1;

Doesn't connect just with
options.ka_time = 1

**Comment by robotconscience** [comment]
Ah! That's good to know. I updated the example quick to reflect that.
