### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by liquidzym** [labatrockwell/ofxLibwebsockets#65]
does anyone got examples working with windows? something weird happening in my case,some of the examples doesn't work i.e  the particles one. some of the example got very lagging issue  as you can see from the video clip. the older version working just great,see the last part of video(but i was build that vs library long time ago can recall which version was)

@mattfelsen does those examples works for you? i'm tested with of 090&vs2015&win10
the testing result video link https://vimeo.com/146878141

**Comment by robotconscience** [comment]
Oof, that lagging is worse than I thought! Diving into it now–sit tight.

**Comment by robotconscience** [comment]
@mattfelsen any insights on windows build? Not working for me at the moment, just getting weird errors once I link...

**Comment by mattfelsen** [comment]
I haven't looked at it recently but was seeing the same slow behavior as @liquidzym for both 32-bit and 64-bit. It was building though!

@liquidzym what is the setup from the end of the video where it's working fine? ofxLibwebsockets master branch, 32-bit, OF 0.9.0?

**Comment by robotconscience** [comment]
Thanks Matt. It's building fine as-is, and the library is building in and of itself... But when I link it, I'm getting weird errors and no connections.

Out-of-the-box, it's super slow overall on Windows. So weird! I'm wondering if the library was built with debug symbols, or something to that end? There's just crazy latency overall.

**Comment by liquidzym** [comment]
hey,thank you for looking into it，@mattfelsen，sorry ,the end of the video which i did complied myself with vs2013,and using OF 0.84,but that's couple of months ago which i think i'm using the older version of ofxlibwebsocket and master branch of the websocket from here https://github.com/warmcat/libwebsockets，maybe the 1.22 version at that time

@robotconscience i don't think the library built with debug symbols,i was double check on that,i also did complied version 1.5 today,same results as 090-vs64 branch

**Comment by robotconscience** [comment]
@liquidzym oof! Not sure what's up then! If you compiled it, can you try libwebsockets' test samples and see if you see the same stuff?

You can also try setting "waitMillis" in the server to a smaller number – e.g. 10 instead of 50
(https://github.com/labatrockwell/ofxLibwebsockets/blob/0.9.0/libs/ofxLibwebsockets/src/Server.cpp#L19)
–and see if that helps? 

Also try taking out the locks in the server update?
https://github.com/labatrockwell/ofxLibwebsockets/blob/0.9.0/libs/ofxLibwebsockets/src/Server.cpp#L218

Let me know if you have any luck there!

**Comment by mattfelsen** [comment]
Good news! I tried bringing waitMillis all the way down to 1ms or even 0ms (in both Server and Client.cpp) and see a massive speedup! I also took out lock/unlock calls and I'm not seeing any weird behavior, though not sure if that means they can/should actually be removed. The sharedcanvas and blob examples are near-instant now. I'm still having trouble connecting from a non-local client, even with the app set to go through both private & public networks, and even with Windows Firewall off entirely, but that's a separate issue. Haven't tested blob_video to see what performance is like (can't get either the graber or videoplayer to work at the moement), and particles also isn't working for me, but this is promising. It's a thanksgiving miracle!

**Comment by liquidzym** [comment]
wow! like @mattfelsen said what a miracle! after way down to 0ms and remove lock&unlock,i only tried 
with server_binary_video example atm,working really great!  i'm going to testing more examples will let you know

**Comment by robotconscience** [comment]
Awesome! The waitMillis came up before, and lws' examples just use 10 so I think we're good! Just need to test with big messages, but should be a-ok. 

Thanks for testing, guys! Will be MIA from computer for a bit, but if one of you want to do a PR to the 0.9.0 branch that'd be awesome. 

@mattfelsen I think that's all we need to merge that into master, correct? I think adding the project on win seems moot with the new projectGenerator, what do you think?

**Comment by mattfelsen** [comment]
Yea I think that's it. I'll send along a PR soon-ish, along with some minor clarifying edits to addon_config.mk. Did you mean the ofxLibwebsocketsLib project and/or prop sheet? If so, I think we can skip it since the new PG makes it so simple to generate/update projects... (I think most of its magic is due to the shiny new icon :smile:) Cheers!

**Comment by mattfelsen** [comment]
@liquidzym this should be good now with #66 merged in. Brett can we close this one?

**Comment by robotconscience** [comment]
@mattfelsen I'll close it when I merge into master on Friday! :+1: 
@liquidzym & @mattfelsen does all look good on the windows side testing-wise? I fried my windows side of my laptop (don't ask), so can only test OS X at the moment...!

**Comment by mattfelsen** [comment]
The blob examples for images looked good when testing before...I still haven't been able to test video (even with k-lite installed I can't play a friggin h.264 video??) but I'll try to test with a depth cam or something soon ha

**Comment by liquidzym** [comment]
@mattfelsen, @robotconscience,sure,you can close this one. thxs!

**Comment by robotconscience** [comment]
Merged. Closing, thanks guys!
