### ISSUE TITLE
osx oF0.9 32 bit

### ISSUE THREAD

**Issue by natxopedreira** [labatrockwell/ofxLibwebsockets#67]
Hi

Its possible to use this addon in oF0.9?, im trying to compile the examples and get 

Undefined symbols for architecture i386

Thanks!

**Comment by robotconscience** [comment]
Hm, it should be! What platform are you on?

**Comment by natxopedreira** [comment]
osx 10.10.5, xcode 6.3.2

**Comment by natxopedreira** [comment]
the exact error is:

  "ofxLibwebsockets::lws_callback(libwebsocket_context*, libwebsocket*, libwebsocket_callback_reasons, void*, void*, unsigned long)", referenced from:
      ofxLibwebsockets::Server::setup(ofxLibwebsockets::ServerOptions) in Server.o

or

"ofxLibwebsockets::lws_client_callback(libwebsocket_context*, libwebsocket*, libwebsocket_callback_reasons, void*, void*, unsigned long)", referenced from:
      ofxLibwebsockets::Client::connect(ofxLibwebsockets::ClientOptions) in Client.o

**Comment by robotconscience** [comment]
Hm, not sure I understand this yet, but the problem is that (for some reason) in 32-bit it's not finding the external functions in ofxLibwebsockets/libs/ofxLibwebsockets/src/Util.cpp

For now, just drop that file into your xcode project, and all will be good!

**Comment by natxopedreira** [comment]
yep, now works, thanks!

**Comment by Samsy** [comment]
Dont know if it is linked..

Xcode 7.0.1

Mac OSX 10.11.2

Undefined symbols for architecture x86_64:
  "ofxLibwebsockets::lws_client_callback(libwebsocket_context*, libwebsocket*, libwebsocket_callback_reasons, void*, void*, unsigned long)", referenced from:
      ofxLibwebsockets::Client::connect(ofxLibwebsockets::ClientOptions) in Client.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
