### ISSUE TITLE
OFX 0.9 Last / Cant compile basic examples

### ISSUE THREAD

**Issue by Samsy** [labatrockwell/ofxLibwebsockets#68]
Dont know if it is linked..

Xcode 7.0.1

Mac OSX 10.11.2

Undefined symbols for architecture x86_64:
"ofxLibwebsockets::lws_client_callback(libwebsocket_context, libwebsocket, libwebsocket_callback_reasons, void, void, unsigned long)", referenced from:
ofxLibwebsockets::Client::connect(ofxLibwebsockets::ClientOptions) in Client.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by robotconscience** [comment]
Ah! Can you try the fix from here:
https://github.com/labatrockwell/ofxLibwebsockets/issues/67

I'm not sure why that file isn't getting added by Xcode anymore. I'll look into it and make sure it's working with the project generator properly. Let me know if that fix works for now!

**Comment by mattfelsen** [comment]
Ran into this too. Just confirming for future readers that Util.cpp was indeed the missing piece.
