### ISSUE TITLE
Build fails whenever I call client's sendBinary method.

### ISSUE THREAD

**Issue by no-wa-ke** [labatrockwell/ofxLibwebsockets#75]
Hi,
This may seem really basic, I want to apologize in advance.
I'm currently running client_hello_world example, and trying to add sendBinary method to it.
I'm putting ofImage as server_binary example does, but when I try to compile it, it throws some errors:

**Undefined symbols for architecture x86_64:
  "void ofxLibwebsockets::Client::sendBinary<ofImage_<unsigned char> >(ofImage_<unsigned char>&)", referenced from:
 ofApp::keyPressed(int) in ofApp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
**
Am I not suppose to call this method?

Thanks

**Comment by no-wa-ke** [comment]
It works when I use unsigned char and size for the arguments, but fails when I use ofImage.

**Comment by robotconscience** [comment]
Hello! Totally not a basic question–and 100% an error in my code. For some reason I set up the Server and Client functions differently.

I just pushed an update that fixes it for you. Thanks for calling that out, and sorry for the bug!

**Comment by no-wa-ke** [comment]
thank you!
