### ISSUE TITLE
'Unlock of unowned mutex' error on VS Debug.

### ISSUE THREAD

**Issue by smallfly** [labatrockwell/ofxLibwebsockets#77]
Hi Brett,

When running a VS project only using a ```ofxLibwebsocket::Server```, I get this 'Unlock of unowned mutex' error message and a call to Abort() is made. See the screen capture below. This happens when compiling in Debug x64 and 8 times out of 10 when compiling in Debug Win32. I did not get this issue when compiling in Release.

![screenshot](http://www.smallfly.com/of/ofxLibwebsockets-unlock-error.JPG)

The issue is linked to the ```unlock()``` call made in the ```Server::threadedFunction()``` method.
To fix this I think that the call ```startThread()``` in the method ```Server::setup()``` should be replaced by ```startThread(true)``` to actually be blocking (as mentioned in the comment beside it).

I guess the same thing should be done for ```ofxLibwebsocket::Client```.

If you want I can make a PR.

Thanks,

**Comment by robotconscience** [comment]
That'd be great! I can test that on OS X as well. Just out of curiosity, what OF version are you using? ofThread seems to have been having lots of little changes lately in master.

**Comment by smallfly** [comment]
Will do. I'm compiling against the current master (and also tried with the 0.9.2).

**Comment by smallfly** [comment]
Hi,

I found a better way to do this.
Let me know if something is wrong.

Thanks!

Hugues.

**Comment by robotconscience** [comment]
Closing issue for now, thanks again for the PR!
